### ISSUE TITLE
Error 0xd8a0a046 while launching offline

### ISSUE THREAD

**Issue by CoopLink** [yellows8/hblauncher_loader#1]
Every time i open the launcher cia, i need to download the payload to enter the HL, it says the payload has been downloaded and the HL starts, but the payload doesnt get on my SD, also, if i run the program without internet, it says error 0xd8a0a046 and i cant do nothing but exit. How can i solve this? Can i download the payload with my pc? My 3ds its normal one Sys:4.2 Emu:10.3 USA linked nands

**Comment by profi200** [comment]
README

**Comment by snuggles08** [comment]
Hold Y on open with internet
