### ISSUE TITLE
Not saving to SD

### ISSUE THREAD

**Issue by S0llux** [yellows8/hblauncher_loader#11]
As title. Release 1.1 isn't saving the payload to SD. At least for me, I can only load when connected to internet.

**Comment by yellows8** [comment]
Are you really not pressing any buttons while the title is running?

**Comment by S0llux** [comment]
Correct, also tried holding the x and y buttons, and it doesn't load the file I got from http://smealum.github.io/3ds/, which I put on the root of the sd and named properly. Would you mind testing it yourself just for confirmation?

**Comment by yellows8** [comment]
It obviously works fine here since before v1.1. release.

**Comment by S0llux** [comment]
have you actually tested it? im honestly unable to use this without an internet connection...

**Comment by yellows8** [comment]
Of course, hence "since before v1.1. release."

**Comment by S0llux** [comment]
Will do. Will take a video trying to launch without, with, then without again. will edit wih link when done.

**Comment by internetakias** [comment]
Can report the same issue at EmuNAND 10.6
