### ISSUE TITLE
Failed to download the actual payload

### ISSUE THREAD

**Issue by Justinleech** [yellows8/hblauncher_loader#12]
Hi I am trying to update my 3ds to 9.2.0 or whatever it is and I am 7.1.0-11. I went through the whole 9.2.0 update walkthrough here:
https://github.com/Plailect/Guide/wiki/9.2.0-Update
Even making sure to replace the sysUpdater cia with the Homebrew Launcher cia. 
Everything works fine as I go through RXTools and download the launcher and can launch the app on my 3ds, but then I get an error that it "failed to download the actual payload  with HTTp: 0xfffffffe"
I have the sysupdater files in my 3ds folder and I figured that I just launch the homebrew app and then it gives me a prompt, but I am stuck at this point.

**Comment by yellows8** [comment]
If it happens multiple times upload a pic.

**Comment by Justinleech** [comment]
![image](https://cloud.githubusercontent.com/assets/17759287/13694929/e166b1c4-e70e-11e5-8fa4-2f7f72fd8417.jpeg)

**Comment by yellows8** [comment]
\*hax payloads obviously don't support <v9.0.

**Comment by Justinleech** [comment]
Can you provide any more help than that? What should I do? I thought the whole point of this was that I am not at that version and am upgrading to that version.

**Comment by yellows8** [comment]
Updating to a particular system-version from pre-v9.0(via gamecard for example) has nothing to do with hblauncher_loader.

**Comment by Justinleech** [comment]
I looked at the guide and saw the error I made. Thanks for giving me such useful information! I feel so much more informed by your clear and full-bodied responses.
