### ISSUE TITLE
Cannot download the payload

### ISSUE THREAD

**Issue by voldart** [yellows8/hblauncher_loader#15]
I think my problem is caused by the new 11.0.0-33 firmware. I just installed am9loaderhax yesterday and when I launch the HBL I encounter with this error :

hblauncher_loader v1.1 by yellows8.
Getting system-version/system-info etc...
Detected system-version: New3ds 11.0.0-33 USA
Since the X button isn't pressed, this will now check for the otherapp payload on SD, with the following filepath: sdmc :
/hblauncherloader_otherapp_payload_NEW-11-0-0-33-USA.bin
Requesting the actual payload URL with HTTP...
Downloading the actual payload with HTTP...
Error: server returned HTTP statuscode 404.
Failed to download the actual payload with HTTP: 0xfffffffe.
If the server isn't down, and the HTTP request was actually done, this may mean your system-version or region isn't supported by the hblauncher-payload currently.
An error occured, please report this to here if it persists (or comment on already existing issue if needed), with an image of your 3DS system: https://github.com/yellows8/hblauncher_loader/issues/
Press the START button to exit.

**Comment by voldart** [comment]
![img_6632](https://cloud.githubusercontent.com/assets/19312518/15192893/f0d57060-17c3-11e6-80f3-5d6b11121af2.JPG)

**Comment by yellows8** [comment]
Just rename the payload on SD to the one for v11.0(see README), since the server payload scripts were not updated yet.

**Comment by guitarguy1133** [comment]
so i installed homebrew loader inside my emunand (with FBI in .CIA format) how would I go about renaming the payload?

**Comment by Scrxtchy** [comment]
A bit of digging around shows us that the 302 redirect from mtheall's response redirects to a 404 page
http://smea.mtheall.com/get_payload.php?version=NEW-11-0-0-33-EUR

You'll know when it's available via that url

**Comment by GoldNoway** [comment]
Hi, 
I have the same problem as voldart with my old 3DS on cfw 11.0, and the hblauncher loader don't seem to recognize the payload, even with an updated name :/

**Comment by lachieh** [comment]
Correct name for a US O3DS is ``hblauncherloader_otherapp_payload_OLD-11-0-0-33-USA.bin``

**Comment by nanos511** [comment]
Hi, i speak spanish so i dont understant all your coments so can you teach me how do to fix that problem i have the same

**Comment by lachieh** [comment]
@nanos511 Sure :+1:
Find the file on the SD card that starts with ``hblauncherloader_otherapp_payload_...``
Change the numbers at the end to match the firmware version of your console.

For example, mine file was named:
``hblauncherloader_otherapp_payload_OLD-10-7-0-32-USA.bin``
But now it is named:
``hblauncherloader_otherapp_payload_OLD-11-0-0-33-USA.bin``

**Comment by kratoz29** [comment]
@lachieh Thanks dude, it worked pretty well.

**Comment by markiejzz** [comment]
Hey guys, same problem here but I can't find the hblauncher playload anywhere on my SD.. I'm on a EU system.. Thanks in advance for your help

**Comment by voldart** [comment]
For people who still have problems, I will paste the link of the guide to install CFW that I used. In the "What you need" part, you can download the correctly named payload specific for your console and regions.

https://github.com/Plailect/Guide/wiki/Part-5-(arm9loaderhax)

**Comment by yellows8** [comment]
Please just download the payload from the proper site(https://smealum.github.io/3ds/#otherapp), with it written to the proper filename on your SD card root as described above.

**Comment by antonio-tnl** [comment]
What do you do if you're on v11? The site only lists options for 9 and 10

**Comment by civita88** [comment]
I also got this error - but I have no payload on my SD card to rename. I have an Old 3DS XL running on 11.0.0-3 USA. What should I do?

**Comment by lachieh** [comment]
1. Go here: https://smealum.github.io/3ds/#otherapp
2. Enter the old firmware version (10-7-0-32).
3. Select your 3DS model _(O3DS/2DS = ``OLD``, N3DS = ``New``)_
4. Select your region region
5. Click 'download otherapp'.
5. Rename the file to ``hblauncherloader_otherapp_payload_OLD-11-0-0-33-USA.bin`` (but obviously change the ``OLD`` and ``USA`` to match your model and region respectively.)
6. Copy the file to the root of your SD.

**Comment by Aisakey** [comment]
Hi,

I followed what was said on this discussion so far, I downloaded the 'otherapp' on the link provided (since it was not present on my SD card), then renamed the file as "hblauncherloader_otherapp_payload_NEW-11-0-0-33-EUR.bin".

It managed to download the payload but now it is stuck on 'the homemenu ropbin is ready' ...
http://puu.sh/p81LA/668c23afaa.JPG
I did something wrong ? 

Thanks

**Comment by rosstex** [comment]
Same issue as OP, looks like the server hasn't been updated. Which payload should I use?

**Comment by Scrxtchy** [comment]
@rosstex Take a look at @lachieh's latest comment, it's pretty straight forward

@Aisakey Are your homebrew menu files still on the storage card? should be a boot.3dsx
It's not an issue of the homebrew launcher, it's done it's job of loading up the *hax

**Comment by rosstex** [comment]
oh durr, thanks @Scrxtchy @lachieh that worked!

**Comment by yellows8** [comment]
The get-payload scripts on the server were finally updated today.
