### ISSUE TITLE
Download Play mode after start the app. 

### ISSUE THREAD

**Issue by mellamoarbaro** [yellows8/hblauncher_loader#16]
The hblauncher loader randomly start the Download Play mode and can't back to the home menu . 
specs: 
`[ New 3ds + A9LH + Luma3DS + sysnand 11.0 ]`

**Comment by yellows8** [comment]
That's rare but normal with the \*hax payload. https://github.com/smealum/ninjhax2.x

**Comment by mellamoarbaro** [comment]
thanks :+1:
