### ISSUE TITLE
Old3DS 11.0.0-28 TWN, no payload

### ISSUE THREAD

**Issue by bakayaro77** [yellows8/hblauncher_loader#19]
Hi, I installed the A9LH to my OLD3ds Taiwan ver., installed the hblauncher loader cia, but cannot use. Seem no payload for Taiwan ver. Thanks a lot!
![2016-07-15 11 58 35](https://cloud.githubusercontent.com/assets/20470094/16863726/54e5e7be-4a88-11e6-9da6-a4e4508d7152.jpg)

**Comment by yellows8** [comment]
Indeed \*hax payloads don't support TWN atm... https://github.com/yellows8/hblauncher_loader/issues/18#issuecomment-232857601
