### ISSUE TITLE
NVER/TIGER spoofing checks for wrong payload

### ISSUE THREAD

**Issue by CrispyYoshi** [yellows8/hblauncher_loader#2]
Is there a way around this, or can we tell it to check a payload at a designated filename? The loader detected I was on 10.3.0-28U when I'm really on a downgraded 9.2U non-XL N3DS running 9.5.0-23U EmuNAND RxTools. When I held Y to download the payload, it downloaded the 10.3.0-28U file (hblauncherloader_otherapp_payload_NEW-10-3-0-28-USA.bin) and crashed. I also tried manually downloading the proper otherapp payload from Smealum's site and renamed it to "hblauncherloader_otherapp_payload_NEW-9-5-0-23-USA.bin" but that didn't work either.

My EmuNAND is spoofing the following titles:

NVER
Title ID: 000400DB20016302
Version: 448

TIGER
Title ID: 0004001000021900
Version: 19465

CVER
Title ID: 000400DB00017302
Version: 10288

Interestingly enough, I ran my physical copy of Cubic Ninja (U) inside this RxTools EmuNAND and scanned the 9.5.0-23U QR code for Ninjhax and it worked.

**Comment by yellows8** [comment]
Rename the manually downloaded payload to "hblauncherloader_otherapp_payload_NEW-10-3-0-28-USA.bin".

**Comment by CrispyYoshi** [comment]
Can't believe I didn't think of doing that: It worked! Thank you!

**Comment by yellows8** [comment]
You're welcome.
