### ISSUE TITLE
Updated to v1.2.0 but version string still v1.1.1

### ISSUE THREAD

**Issue by jamesyc** [yellows8/hblauncher_loader#22]
The version for the top screen doesn't seem to be updated.

**Comment by yellows8** [comment]
Huh?

**Comment by jamesyc** [comment]
I installed the v1.2 release CIA, but when I run the homebrew launcher, the version still states "1.1.1"

**Comment by yellows8** [comment]
hblauncher_loader's version has nothing to do with hbmenu......

**Comment by jamesyc** [comment]
... let me get back to you after I drink some coffee
