### ISSUE TITLE
Compiling issues

### ISSUE THREAD

**Issue by Arch9SK7** [yellows8/hblauncher_loader#23]
yellows8 i cant seem to compile the source for this do you know why?

when i try this is what i get 

C:\hblauncher_loader-1.2>make
builtin_rootca.der
hblauncher_loader.c
arm-none-eabi-gcc -MMD -MP -MF /c/hblauncher_loader-1.2/build/hblauncher_loader.d -g -Wall -O2 -mword-relocations -fomit-frame-pointer -ffunction-sections -march=armv6k -mtune=mpcore -mfloat-abi=hard -mtp=soft -I/c/hblauncher_loader-1.2/include -I/c/devkitPro/libctru/include -I/c/hblauncher_loader-1.2/build -DARM11 -D_3DS -DVERSION=\"v1.2\"  -c /c/hblauncher_loader-1.2/source/hblauncher_loader.c -o hblauncher_loader.o
c:/hblauncher_loader-1.2/source/hblauncher_loader.c: In function 'http_getactual_payloadurl':
c:/hblauncher_loader-1.2/source/hblauncher_loader.c:39:35: error: 'HTTPC_METHOD_GET' undeclared (first use in this function)
  ret = httpcOpenContext(&context, HTTPC_METHOD_GET, requrl, 1);
                                   ^
c:/hblauncher_loader-1.2/source/hblauncher_loader.c:39:35: note: each undeclared identifier is reported only once for each function it appears in
c:/hblauncher_loader-1.2/source/hblauncher_loader.c:39:53: warning: passing argument 3 of 'httpcOpenContext' makes integer from pointer without a cast [-Wint-conversion]
  ret = httpcOpenContext(&context, HTTPC_METHOD_GET, requrl, 1);
                                                     ^
In file included from c:/devkitPro/libctru/include/3ds.h:42:0,
                 from c:/hblauncher_loader-1.2/source/hblauncher_loader.c:7:
c:/devkitPro/libctru/include/3ds/services/httpc.h:34:8: note: expected 'u32 {aka long unsigned int}' but argument is of type 'char _'
 Result httpcOpenContext(httpcContext *context, char_ url, u32 use_defaultproxy);
        ^
c:/hblauncher_loader-1.2/source/hblauncher_loader.c:39:8: error: too many arguments to function 'httpcOpenContext'
  ret = httpcOpenContext(&context, HTTPC_METHOD_GET, requrl, 1);
        ^
In file included from c:/devkitPro/libctru/include/3ds.h:42:0,
                 from c:/hblauncher_loader-1.2/source/hblauncher_loader.c:7:
c:/devkitPro/libctru/include/3ds/services/httpc.h:34:8: note: declared here
 Result httpcOpenContext(httpcContext _context, char_ url, u32 use_defaultproxy);
        ^
c:/hblauncher_loader-1.2/source/hblauncher_loader.c:49:8: warning: implicit declaration of function 'httpcAddTrustedRootCA' [-Wimplicit-function-declaration]
  ret = httpcAddTrustedRootCA(&context, (u8_)builtin_rootca_der, builtin_rootca_der_size);
        ^
c:/hblauncher_loader-1.2/source/hblauncher_loader.c: In function 'http_download_payload':
c:/hblauncher_loader-1.2/source/hblauncher_loader.c:78:35: error: 'HTTPC_METHOD_GET' undeclared (first use in this function)
  ret = httpcOpenContext(&context, HTTPC_METHOD_GET, url, 1);
                                   ^
c:/hblauncher_loader-1.2/source/hblauncher_loader.c:78:53: warning: passing argument 3 of 'httpcOpenContext' makes integer from pointer without a cast [-Wint-conversion]
  ret = httpcOpenContext(&context, HTTPC_METHOD_GET, url, 1);
                                                     ^
In file included from c:/devkitPro/libctru/include/3ds.h:42:0,
                 from c:/hblauncher_loader-1.2/source/hblauncher_loader.c:7:
c:/devkitPro/libctru/include/3ds/services/httpc.h:34:8: note: expected 'u32 {aka long unsigned int}' but argument is of type 'char *'
 Result httpcOpenContext(httpcContext *context, char_ url, u32 use_defaultproxy);
        ^
c:/hblauncher_loader-1.2/source/hblauncher_loader.c:78:8: error: too many arguments to function 'httpcOpenContext'
  ret = httpcOpenContext(&context, HTTPC_METHOD_GET, url, 1);
        ^
In file included from c:/devkitPro/libctru/include/3ds.h:42:0,
                 from c:/hblauncher_loader-1.2/source/hblauncher_loader.c:7:
c:/devkitPro/libctru/include/3ds/services/httpc.h:34:8: note: declared here
 Result httpcOpenContext(httpcContext _context, char_ url, u32 use_defaultproxy);
        ^
c:/hblauncher_loader-1.2/source/hblauncher_loader.c:95:8: warning: implicit declaration of function 'httpcAddDefaultCert' [-Wimplicit-function-declaration]
  ret = httpcAddDefaultCert(&context, SSLC_DefaultRootCert_DigiCert_EV);
        ^
c:/hblauncher_loader-1.2/source/hblauncher_loader.c:95:38: error: 'SSLC_DefaultRootCert_DigiCert_EV' undeclared (first use in this function)
  ret = httpcAddDefaultCert(&context, SSLC_DefaultRootCert_DigiCert_EV);
                                      ^
c:/hblauncher_loader-1.2/source/hblauncher_loader.c:109:8: error: too few arguments to function 'httpcGetResponseStatusCode'
  ret = httpcGetResponseStatusCode(&context, &statuscode);
        ^
In file included from c:/devkitPro/libctru/include/3ds.h:42:0,
                 from c:/hblauncher_loader-1.2/source/hblauncher_loader.c:7:
c:/devkitPro/libctru/include/3ds/services/httpc.h:85:8: note: declared here
 Result httpcGetResponseStatusCode(httpcContext _context, u32_ out, u64 delay);
        ^
c:/hblauncher_loader-1.2/source/hblauncher_loader.c: In function 'load_hblauncher':
c:/hblauncher_loader-1.2/source/hblauncher_loader.c:264:18: warning: passing argument 1 of 'APT_CheckNew3DS' from incompatible pointer type [-Wincompatible-pointer-types]
  APT_CheckNew3DS(&new3dsflag);
                  ^
In file included from c:/devkitPro/libctru/include/3ds.h:31:0,
                 from c:/hblauncher_loader-1.2/source/hblauncher_loader.c:7:
c:/devkitPro/libctru/include/3ds/services/apt.h:388:8: note: expected 'u8 \* {aka unsigned char _}' but argument is of type '_Bool *'
 Result APT_CheckNew3DS(u8 *out);
        ^
c:/hblauncher_loader-1.2/source/hblauncher_loader.c:275:18: warning: implicit declaration of function 'AM_GetTitleInfo' [-Wimplicit-function-declaration]
  if(ret==0)ret = AM_GetTitleInfo(MEDIATYPE_NAND, 1, &menu_programid, &menu_title_entry);
                  ^
c:/hblauncher_loader-1.2/source/hblauncher_loader.c: In function 'main':
c:/hblauncher_loader-1.2/source/hblauncher_loader.c:479:9: error: too many arguments to function 'httpcInit'
   ret = httpcInit(0);
         ^
In file included from c:/devkitPro/libctru/include/3ds.h:42:0,
                 from c:/hblauncher_loader-1.2/source/hblauncher_loader.c:7:
c:/devkitPro/libctru/include/3ds/services/httpc.h:23:8: note: declared here
 Result httpcInit(void);
        ^
make[1]: *_\* [hblauncher_loader.o] Error 1
make: **\* [build] Error 2

C:\hblauncher_loader-1.2>

sorry for it being messy...

**Comment by yellows8** [comment]
Changelog specifically mentioned "latest ctrulib".....

**Comment by Arch9SK7** [comment]
Right my bad... thank you.

**Comment by nikhil925** [comment]
Hi, I'm a newbie to all this hacking stuff.
So I just completed all the steps from 3ds.guide but I can't open homebrew. 
I didn't make any mistakes apart from one where I injected the FBI into hs.app before injecting into .app for my region which I did after. I also injected the FBI in the hs.app again. 

Thanks

**Comment by yellows8** [comment]
That has *absolutely* *nothing* to do with this issue, there's already github-issues for v11.3 if that's what you meant...
