### ISSUE TITLE
Incorrect version reported on main menu

### ISSUE THREAD

**Issue by PolarisBeaver** [yellows8/hblauncher_loader#26]
I have updated to the new version 1.2, reinstalling HB_launcherloader.cia with FBI, overwriting it and while I get prompted for a pin (suggesting the update is installed on my 3ds), the version reported on the main menu with the blue wavy background is 1.1.0

Is this an oversight of a simple string or am I truly not updated? Any way to test?

**Comment by ihaveamac** [comment]
hblauncher_loader version isn't the same as homebrew launcher. you should update boot.3dsx: https://smealum.github.io/ninjhax2/boot.3dsx

**Comment by yellows8** [comment]
#22

**Comment by PolarisBeaver** [comment]
Whoops, sorry! Thank you.
