### ISSUE TITLE
Error downloading payload

### ISSUE THREAD

**Issue by 20325** [yellows8/hblauncher_loader#29]
Dusted off an OLD3ds running 4.5.0-10 and followed the guide.  

![file_000](https://cloud.githubusercontent.com/assets/22041619/18297176/5f6ce15e-7474-11e6-8f73-8669a6412359.jpeg)

**Comment by yellows8** [comment]
"4.5.0-10" Notice the allowed sysver range... https://smealum.github.io/3ds/#otherapp
