### ISSUE TITLE
HB Launcher blocked for 11.1.0-34E

### ISSUE THREAD

**Issue by daemon79** [yellows8/hblauncher_loader#30]
Just used Plailect's guide to install custom firmware and at the stage where I try to start HB Launcher from the Home Screen but instead get the following error:

"Failed to request the actual payload URL : 0xd8a0a046
No usable Internet-connection is likely available.
Press the START button to exit." 

Is this because I updated to the latest system update (11.1.0-34E)? Is there a work around such as downgrading to the previous version?

**Comment by ihaveamac** [comment]
*hax still needs updating for 11.1.0 which only just came out ~two hours ago.

**Comment by kroenem** [comment]
"Oh, I'll just leave it to tomorrow night"
I said.
![screen shot 2016-09-13 at 12 37 05 am](https://cloud.githubusercontent.com/assets/22166131/18463852/3fd36d06-794a-11e6-84d7-e0608a3647d8.png)
the guide said.
"^%&*$&*^$"
I said just now after needing some things for Wednesday
