### ISSUE TITLE
lblauncher-loader v1.2- error payload - 404 - 0xfffffffe - n2ds Sys 11.1.0-34E

### ISSUE THREAD

**Issue by rfcs33** [yellows8/hblauncher_loader#31]
hi,
Cannot have payload url with this firmware version 
My n2ds is now with Sys 11.1.0-34E

hope u can help me

thanks

**Comment by BrunoShin** [comment]
I'm having a similar issue. My version is 11.1.0 - 34U

I was on the section VI of the part 3 of plailect guide

I took a photo of the error screen:

![20160913_125828](https://cloud.githubusercontent.com/assets/22176323/18481775/dcdeb678-79b3-11e6-8357-a2a4bdfed2e7.jpg)

**Comment by Francisco0021** [comment]
"This is Safe"
They Said...

**Comment by Webbeh** [comment]
...Same error.

**Comment by yellows8** [comment]
...

**Comment by rfcs33** [comment]
It´s working again.
Thanks
