### ISSUE TITLE
hbloader failed to download the actual payload with httpc

### ISSUE THREAD

**Issue by dark9011** [yellows8/hblauncher_loader#32]
New timer here, doing the entire arm9loaderhax, I got the the very end no problem.. until I came into the step where I load into Homebrew and dump the DSP, I had no issues loading into it before the updating part and fbi injection, but now I can't open Homebrew menu because I get this error. I dont know what to do, I followed all the steps. 

I'm on firmware 11.1.0.34U using New3DS.
![imag0075](https://cloud.githubusercontent.com/assets/5686533/18498461/3b098b36-79fc-11e6-9fdd-9c2af0c06c60.jpg)

I tried the method from the previous issue, which is downloading the file and renaming it and placing it sdroot, but it didnt work for me either.

**Comment by yellows8** [comment]
...... https://github.com/smealum/ninjhax2.x/issues/14#issuecomment-246891475
