### ISSUE TITLE
Return to homemenu error

### ISSUE THREAD

**Issue by suzsuzuki** [yellows8/hblauncher_loader#33]
I'm using version 1.2 at A9LH n3DS FW 11.0. Every time I return to homemenu after open the cia the system give me an error saying something like "An error has occurred. Please save your data in any software currently in use, and then restart the system". But everything works fime after that.

If I press the home button while in hbl and press start and choose return to homemenu, the error occurs again but this time the power button don't work. Also, I can't open any apps, only black screen and need to force power down.

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_homemenuhax#usage-notes-for-sdiconhax

**Comment by suzsuzuki** [comment]
Sorry for posting known issue
