### ISSUE TITLE
error 404

### ISSUE THREAD

**Issue by LokiGrants** [yellows8/hblauncher_loader#34]
I updated my hblauncher to 1.2 today and can't get it to work anymore. Keep getting error 404 with code 0xfffffffe. The otherapp payload is both in the root of the sd and in the hblauncherloader folder and with the correct name. So it shouldn't even check online to download. What am I doing wrong? And the internet is working just fine outside of it.

**Comment by yellows8** [comment]
What's the displayed system-version?

**Comment by LokiGrants** [comment]
NEW 3DS 11.0.0 - 33U

**Comment by yellows8** [comment]
Did you ever install a modified homemenu?

**Comment by LokiGrants** [comment]
Never. I use sysnand with Luma.

**Comment by criminallysane** [comment]
Need some help here. Followed instructions [here](https://3ds.guide/installing-arm9loaderhax) to the letter, starting at the beginning. No issues until it asks me to open Homebrew Launcher from the menu and Select DSP Dump. Homebrew opens and reports a 404 error and directs me here to resolve. I can't do anything beyond that step.

**Comment by criminallysane** [comment]
I've got old 3ds, 11.3.0-36U

**Comment by w1ngman07** [comment]
I am having the same error.  just did this last night on another new 3ds xl.  11.2.0.35u originally

**Comment by w1ngman07** [comment]
mine is a galaxy 3ds.  should this matter? what is yours criminallysane?
