### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by gamerb0y** [yellows8/hblauncher_loader#35]
My old 3ds is running on 4.5 sysnand but it has 11.0.0-33 emunand (using Gateway). I tried installing the cia onto the emunand but it doesn't seem to work. Is it because my sysnand is too old?

**Comment by yellows8** [comment]
"not working" isn't helpful...

**Comment by gamerb0y** [comment]
Sorry. When I go to open HB Launcher, it seems fine for a second and says it's ready, but then the bottom screen turns red

**Comment by yellows8** [comment]
SD /boot.3dsx failed to load...

**Comment by gamerb0y** [comment]
Thanks! I deleted the boot file that was in the SD already and reinstalled it, and it worked this time
