### ISSUE TITLE
Merge new Animated Banner?

### ISSUE THREAD

**Issue by SirBeethoven** [yellows8/hblauncher_loader#36]
Hello yellows or smea! There's a new banner that the creator of the Mario kart custom track hack made. Here it is! https://github.com/mariohackandglitch/hblauncher_loader Could you possibly merge it into the main git? Thank you!!! Have a good weekend!

**Comment by yellows8** [comment]
#28

**Comment by SirBeethoven** [comment]
Sorry yellows! Didn't know!

Anyways, have a good weekend!
