### ISSUE TITLE
Homebrew Launcher and Download Play

### ISSUE THREAD

**Issue by IngeniousDefault** [yellows8/hblauncher_loader#38]
When I launch the Homebrew Launcher_loader on my 3DS the play time of the Download Play app in the Activity Log is marked as used on that day and the play time gets higher (a few seconds in the launcher = +3 minutes of play time for the Download Play app). Why is that and can I somehow avoid it? I also seem to loose applications in my list of games that I played.
This only happens with a CFW. On my normal system with Cubic Ninja (Ninjhax 2.7) there is no change at all.

**Comment by yellows8** [comment]
"This only happens with a CFW. " Then ask @ github-issues for that "cfw".
