### ISSUE TITLE
yellow screen on launching any app in homebrew launcher 1.1.3s,1.1.1,1.1.0

### ISSUE THREAD

**Issue by Ekam3284** [yellows8/hblauncher_loader#39]
I HAVE TRIED ALL HBL LOADERS 1.1.3s,1.1.1,1.1.0 BUT APPS DONOT OPEN ON ANY pls help i am stuck whenever i start an app the bottom screen turns yellow and the 3ds frezes i am on firmware  11.1.0-34U with stellhax and bashaxx  

the apps were working fine when i was on 11.0.0-33U pls help

**Comment by Davidosky99** [comment]
Calm down

**Comment by Ekam3284** [comment]
pls help

**Comment by yellows8** [comment]
You can't do anything about it *yourself* atm.

https://www.3dbrew.org/wiki/11.1.0-34#loader
