### ISSUE TITLE
Failed to request payload 0xd8a0a028

### ISSUE THREAD

**Issue by lytesenthedarc** [yellows8/hblauncher_loader#43]
Hello Yellows8, hope all is well. I am having issues accessing the hblauncer and I was hoping you could help me.I ran a similar setup on an old 3ds a week ago without any issue. Tonight however, as I'm setting up a New 3ds, I have been stuck on that error message. Is the server down, or is there another issue I need to be worried about? Thank you for your time.

**Comment by tsm28** [comment]
Getting the same error on an old 3DSXL.  First time trying this and following the instructions from 3ds.guide

**Comment by cangoektas** [comment]
Same here. Following 3ds.guide for a 3DS XL (OLD-11-2-0-35-EUR). I read somewhere that the servers don't have the latest payloads. Should we download an older one, rename and place them on the SD card manually?

**Comment by cangoektas** [comment]
Following the instructions on the README:

> This will first attempt to load the payload from SD, if that isn't successful it will then automatically download the payload for your system with HTTP. SD payload loading can be skipped if you hold down the X button. If you don't hold down the Y button, this will write the downloaded payload from HTTP to SD, if it actually downloaded it via HTTP.

> The exact filepath used for the SD payload depends on your system. Since this app can handle writing the payload here itself, writing the payload here manually isn't really needed. Example SD filepath with New3DS 10.1.0-27U: "/hblauncherloader/hblauncherloader_otherapp_payload_NEW-10-1-0-27-USA.bin". The Old3DS filepath for the same system-version and region as that example is the same, except that "OLD" is used instead of "NEW".

I just downloaded otherapp _OLD-11-1-0-35-EUR_ (because the one for my current firmware is not on [https://smealum.github.io/3ds/#otherapp)](https://smealum.github.io/3ds/#otherapp), renamed it to match my firmware version _hblauncherloader_otherapp_payload_OLD-11-2-0-35-EUR.bin_ and put it into the hblauncherloader folder. Didn't do anything, unfortunately. 🤔

**Comment by barry1985** [comment]
I've tried installing this for the first time, followed the guide and am experiencing the same issue. Hopefully this will be resolved soon.

**Comment by scjacobi** [comment]
Having the same problem, error code 0xd8a0a028. On system 11.2.0-35U, installed hblauncher.cia following this guide: https://3ds.guide/installing-arm9loaderhax Got to step 13 of "Section VI - Finalizing setup" when I encounter a similar error to puddlesvgc's image with a different error code. So I can't perform the DSP Dump step. Not sure if I can proceed or not. Any suggestions? Thanks.

**Comment by lytesenthedarc** [comment]
scjacobi are you using old or new 3ds?

**Comment by scjacobi** [comment]
Old.  

I also tried the trick that cangoektas tried, downloading the latest version of the payload that is available on smealum's site, OLD 11-1-0-35-U, and renamed the file hblauncherloader_otherapp_payload_OLD-11-2-0-35-USA.bin, but no dice.

**Comment by lytesenthedarc** [comment]
scjacobi, the problem I am having currently is with the New 3ds. Fortunately for you, I had successfully completed the process on the old 3ds running 11.2.0-35U last week; The server seemed to be working fine then. I've gone ahead and uploaded the file that I had in my hblauncherloader folder on the root of the SD card. Unzip the file and put OLD-11-2-0-35-USA.bin into that folder. Let me know if it works for you. Good luck! 
[OLD-11-2-0-35-USA.bin.zip](https://github.com/yellows8/hblauncher_loader/files/616754/OLD-11-2-0-35-USA.bin.zip)

**Comment by yellows8** [comment]
AFAIK the server is fine, hence why the same older issue was closed(when accessed with curl/etc). Try changing the system's DNS config to 8.8.8.8(and make sure wifi was actually usable on the system to begin with).

**Comment by lytesenthedarc** [comment]
Hey yellows8, thank you for your response. I am able to access the internet, eshop, etc without issue. I have tried as you suggested and changed the system's DNS config to 8.8.8.8 and had no luck.

**Comment by lytesenthedarc** [comment]
Also, I don't know if it makes a difference or not, but I removed the OLD-11-2-0-35-USA.bin file my old 3ds had downloaded last week, and it is having the same problem as the New 3ds I am currently trying to update. I did not change any settings on the old 3ds since before loading the hblauncher cia on it. Thank you!

**Comment by cangoektas** [comment]
Hi yellow8, thanks for looking into it. 👍

I also changed my DNS settings and made sure that the internet access was fine, but I'm still getting the same error. Let me know if I can test anything else to track this down.

**Comment by madraff** [comment]
Hey yellow8. 

Got the same error with a 2DS (OLD-11-2-0-35-EUR). Any suggestions?

**Comment by yellows8** [comment]
Just tested it here and got the same error(even though accessing it with web-browser / non-3ds works), have to debug later...

**Comment by NataliePequeno** [comment]
I've just bought a 2DS on 9.2, got to the very last step which is to open the Home-brew app and run DSP Dump but it wouldn't load. So this is a server issue?

**Comment by sillvana662** [comment]
Same error. Thanks for help

**Comment by yellows8** [comment]
It's fixed now AFAIK.

**Comment by lytesenthedarc** [comment]
It works! You are awesome yellows8, thank you for everything!
