### ISSUE TITLE
Yellows8 need payload url

### ISSUE THREAD

**Issue by Mexicanman544** [yellows8/hblauncher_loader#48]
when I try to open Homebrew luncher on 3ds its saying that i need the actual payload url with HTTPC

**Comment by Granmazza** [comment]
Same issue on 2DS 11.2.0-E35, perhaps the server is down at the moment?

**Comment by yellows8** [comment]
Huh? "server is down" no

**Comment by santler** [comment]
Hey yellows8, thanks for the reply! I have the same issue, somehow the homebrewlauncher_loader can't access the URL

"Failed to request the actual payload URL: 0xd8a0a028."

I'm also on 2DS 11.2.0-E35

**Comment by Mexicanman544** [comment]
I believe it is that im on a old 3ds same update

**Comment by yellows8** [comment]
Make sure that your network config doesn't use anything unusual.

**Comment by Mexicanman544** [comment]
Do you have any explains of this unusual things.

**Comment by nakku1617** [comment]
i have a same problem

**Comment by yellows8** [comment]
Also make sure that smea.mtheall.com is accessible from your network.

**Comment by Granmazza** [comment]
If so many of us are getting this issue at the sake exact moment than perhaps the problem isn't our network, that would be quite a coincidence

**Comment by Granmazza** [comment]
I can access smea.mtheall.com just fine

**Comment by nakku1617** [comment]
smea.mtheall.com me too

**Comment by Neostromo** [comment]
Fine for me too.

**Comment by Mexicanman544** [comment]
Do I type that in the 3ds's internet

**Comment by Neostromo** [comment]
Yes. (I guess...)

**Comment by Mexicanman544** [comment]
Then what do we after that

**Comment by nakku1617** [comment]
i don't know

**Comment by joaodacostaplumbee** [comment]
I can access smea.mtheall.com from the 3ds as well

**Comment by santler** [comment]
Working fine on the 3DS, just getting a security message beforehand. Don't know if that's important.

**Comment by yellows8** [comment]
Just tested it & getting that error with menuhax_manager with stuff accessing \*.mtheall.com.

**Comment by Granmazza** [comment]
So the issue isn't on our side?

**Comment by nakku1617** [comment]
i don't understand ? server down ?

**Comment by marianocibelli** [comment]
Im having the same issue on a N3DS

**Comment by nakku1617** [comment]
i have a Old 3ds

**Comment by Granmazza** [comment]
So does this mean that while the server appears to work properly our queries for the payload file are getting refused/generating errors?

**Comment by nameghino** [comment]
Same with an old 3DS XL here, I can access smea.mtheall.com just fine.

**Comment by nakku1617** [comment]
I think it is working on it (sry for my english i'm french )

**Comment by Mexicanman544** [comment]
My is error code 012-1511

**Comment by nameghino** [comment]
FYI, it is working now

**Comment by yellows8** [comment]
Fixed by mtheall.

**Comment by Anonstoner420** [comment]
having same problem on N3ds xl. possible server overload?

**Comment by Anonstoner420** [comment]
oh nvm

**Comment by nakku1617** [comment]
good job man the best !!!

**Comment by nakku1617** [comment]
thanks :)

**Comment by Neostromo** [comment]
Thanks, you're the best!

**Comment by santler** [comment]
Everything fixed, thanks a lot!

**Comment by joaodacostaplumbee** [comment]
Confirmed working now on NEW 11.2.0.35-E 
Thanks! :)

**Comment by Mexicanman544** [comment]
Got it to work

**Comment by Granmazza** [comment]
Thanks dude works like a charm now! Just out of curiosity, how did you fix it?

**Comment by yellows8** [comment]
It was the same crypto cipher config issue as last time this error happened.

**Comment by Mexicanman544** [comment]
My 3ds gad that stupid parent lock on it and i took it off and it worked for me
