### ISSUE TITLE
Failed to request payload 0xd8a0a028

### ISSUE THREAD

**Issue by joaodacostaplumbee** [yellows8/hblauncher_loader#49]
Just like many other people in this issue
https://github.com/yellows8/hblauncher_loader/issues/43

I did try renaming the payload to hblauncherloader_otherapp_payload_NEW-11-2-0-35-EUR.bin and place it both in the root of the sdcard and in /hblauncherloader. No success there.
I also tried changing the primary dns to 8.8.8.8, equally unsuccessful. 

Any clues?
Cheers!

**Comment by Granmazza** [comment]
Commenting here as well just to keep myself posted on any developments on this issue. 
Joao, we have the same firmware version so perhaps the root of the issue is the same.

**Comment by juggalotoxic** [comment]
fixed it with an old 3ds

**Comment by Neostromo** [comment]
I've been having the same problem.

**Comment by santler** [comment]
Same here, #48 talks about the same topic. I struggle with the same problem, same firmware but on OLD (2DS).
I also tried to put the payload into the SD (in several folders and with several names), but that's not possible anymore, is it?

**Comment by yellows8** [comment]
#48
