### ISSUE TITLE
Failed to download the actual payload with HTTP: 0xfffffffe

### ISSUE THREAD

**Issue by Brennen1013** [yellows8/hblauncher_loader#50]

**Comment by Brennen1013** [comment]
I'm currently at Mexico and this just so happens to be the first issue I've gotten with homebrew, any ideas?

**Comment by yellows8** [comment]
If you're on v11.3 \*hax payload doesn't support it yet .............

**Comment by Brennen1013** [comment]
Will there be an estimated time for it?

**Comment by yellows8** [comment]
https://twitter.com/smealum/with_replies

**Comment by Brennen1013** [comment]
Appreciate the quick response

**Comment by Pkrockinomega** [comment]
I just hacked my 3DS yesterday.
When smea says the compatibility update is live, I just run luma3ds to install the latest nightly, correct?
