### ISSUE TITLE
Won't launch

### ISSUE THREAD

**Issue by captainloozer** [yellows8/hblauncher_loader#52]
Says system version isn't supported.  Followed a guide on 3ds.guide and it said to update to the latest before installing hblauncher.  Latest is 11.2.0.36.

**Comment by LilyDiamonds** [comment]
I have the same problem, but I haven't found someone to help me :/

**Comment by LilyDiamonds** [comment]
It says: 

hblauncher_loader v1.2 by yellows8.
Requesting the actual payload with HTTPC...
Dowloading the actual payload with HTTPC...
Error: server returned HTTPC statuscode 404.
Failed to download the actual payload with HTTP: 0xfffffffe.

**Comment by LokeYourLord** [comment]
That is because the otherapp.bin payload hasn't update yet, when that happens everyone will be able to use the Homebrew Launcher again, but for now, everyone who updated to 11.3.0-36 will just have to wait.

**Comment by J3diMindtrick2** [comment]
@LokeYourLord  do you know how long this takes "usually"?
And how do i know whether or nor they have updated already, is there a place i can check this? 
Sorry, I'm new to this, hope i'm not bothering you too much

**Comment by Barben360** [comment]
@J3diMindtrick2 a few days probably ? You can check it directly on this github, on "Code" section above this page.

**Comment by LokeYourLord** [comment]
You can easily check for updates here: https://smealum.github.io/3ds/#otherapp

If you follow the link, it will ask you to enter a number. If you pick either Old/New and then 11 and then the number behind that should be a 3, if 3 is not available then it hasn't been updated yet.

Image below:
![update](https://cloud.githubusercontent.com/assets/5807595/22746277/834ba78a-ee23-11e6-9ab2-1c06efd9cffe.png)

**Comment by LokeYourLord** [comment]
@J3diMindtrick2 It "usually" takes a couple of weeks depending on how hard it is for them to update the payload (it depends on how hard Nintendo tried patching the current payload).

I really don't want to say anything when it comes to assuming an ETA, but i would say within 1-2 weeks we should have the update, no longer than that, though it some few times has taken longer.

**Comment by LokeYourLord** [comment]
If you wan't to use Homebrew Apps, just find the .cia equivalent instead and install that through FBI, almost all Homebrew apps have a .cia equivalent, like CHMM2 has a .cia to install.

**Comment by yellows8** [comment]
https://github.com/yellows8/hblauncher_loader/commit/df5fb90c639c7bfab37d746e690b8035408dc4bc
