### ISSUE TITLE
No *hax payload for Old3DS 11.3.0-36E

### ISSUE THREAD

**Issue by jakem72360** [yellows8/hblauncher_loader#53]
I got an error 404 whilst trying to launch the homebrew menu from my home menu. My system is an Old3DS XL on version 11.3.0-36E (with A9LH). I cannot find an otherapp payload on http://smealum.github.io/3ds/. I have a working internet connection BTW and have attached an image on the error.
![img_20170207_231658](https://cloud.githubusercontent.com/assets/7912205/22690890/edd0c3e4-ed8b-11e6-8807-d26712899a79.jpg)

**Comment by ProfMozz** [comment]
I have the same issue, but my Old3DS XL is on 11.3.0-36U. I just updated a few minutes ago as I needed to use PokéBank and HB (.cia) was working properly before the update.

**Comment by weirdal3333** [comment]
The homebrew hax-payloads are outdated, it usually takes a day or two for yellows8 to upload the new hax-payload.

**Comment by yellows8** [comment]
"or yellows8 " *smea

This is not the place for {supported hax-payload system-versions}.

https://twitter.com/smealum/with_replies
