### ISSUE TITLE
HBL doesn't download payload 

### ISSUE THREAD

**Issue by AnthonyUDT** [yellows8/hblauncher_loader#54]
![photo feb 07 7 53 54 pm](https://cloud.githubusercontent.com/assets/25626288/22720282/7d9602d6-ed6f-11e6-8380-98fed8064a15.jpg)
Hello i first want to say I'm new to CFW and i'm not sure how to fix this issue i am on new 3ds on     
(11.3.0-36u) and this problem was caused when i was prompted to update my 3ds to latest firmware i was on (11.0.0-33u) so i updated and then i couldn't load HBL from cia on my home screen and was prompted with the screenshot above.

**Comment by NexoCube** [comment]
lol, 11.3 "fixed" gspwn so we need to wait for yellows8 to update this (to patch otherapp.bin -> .text)

**Comment by AnthonyUDT** [comment]
@NexoCube so how long will it take for them to update otherapp.bin ?

**Comment by NexoCube** [comment]
@AnthonyUDT i don't know, check smealum twitter for updates

**Comment by AnthonyUDT** [comment]
ok thank you for letting me know
