### ISSUE TITLE
hblauncher not working

### ISSUE THREAD

**Issue by mor4mel** [yellows8/hblauncher_loader#55]
I fallowed the 3ds guide... now when I try to launch homebrew from the home menu I get a message that the payloads
![20170208_003738](https://cloud.githubusercontent.com/assets/25633326/22729930/b4b6c0f0-ed99-11e6-865c-8bcc13a282b3.jpg)

**Comment by ajite** [comment]
Did you update your system this morning?

**Comment by Barben360** [comment]
That is normal, you are in 11.3.0-36 as ajite said. Don't worry, a new release of homebrew launcher payloads should be released soon. For the moment you can't launch it. I guess you are at "DSP dump" step of your tutorial. Don't worry, it is not a big deal, you can still use a9lh normally without homebrew launcher for the moment, and do it later.
