### ISSUE TITLE
Can't open homebrew

### ISSUE THREAD

**Issue by nikhil925** [yellows8/hblauncher_loader#56]
Hi, I'm a newbie to all this hacking stuff.
So I just completed all the steps from 3ds.guide but I can't open homebrew.
I didn't make any mistakes apart from one where I injected the FBI into hs.app before injecting into .app for my region which I did after. I also injected the FBI in the hs.app again.
Thanks

**Comment by yellows8** [comment]
" can't open homebrew." Huh?

**Comment by nikhil925** [comment]
Just when I click the application on the home menu. It doesn't open and comes up with that screen.

**Comment by nikhil925** [comment]
*homebrew launcher

**Comment by nikhil925** [comment]
![Uploading IMG_20170209_182738.jpg…]()

**Comment by yellows8** [comment]
Retry image upload?

**Comment by Tupsi2202** [comment]
![img_0976](https://cloud.githubusercontent.com/assets/25680506/22816662/98ac384c-ef63-11e6-9b6b-9fae70cdadd5.JPG)

same problem for me.
FW 11.3.0-36E

**Comment by Rowlet700** [comment]
Same problem with all FW 11.3, I guess. Would you please update the payload?

**Comment by MasterOfMLG** [comment]
Question where would you get that payload?

**Comment by yellows8** [comment]
https://github.com/yellows8/hblauncher_loader/blob/master/ISSUE_TEMPLATE.md
