### ISSUE TITLE
Error: server returned HTTP statuscode 404

### ISSUE THREAD

**Issue by press88** [yellows8/hblauncher_loader#57]
Do NOT ask about {supported system-versions} here for *hax payload, completely wrong place for that.
Failed to download the actual payload wilth HTTP: 0xfffffffe

If the server is down, an the HTTP request was actually done, ths may mean your-system version or region isn't supported by the *hax payload currently.

n3DS Luma 6.6 11.3.0-36E

**Comment by clasher58** [comment]
SoundHax also crashes on launch so it could be the new system update...
