### ISSUE TITLE
Reporting error code.

### ISSUE THREAD

**Issue by Rowlet700** [yellows8/hblauncher_loader#58]
00001000
01fcf000
d8e17406

What's the issue?

**Comment by Rowlet700** [comment]
If you want photos I'll post it for you.

**Comment by ajite** [comment]
I just got the same issue! I run 11.3.0-36U and opened Homebrew to see if the new payload is available.

**Comment by FenrirWolf** [comment]
You need to update to the latest version of the CIA, then update to the latest version of Luma if you're using that.

**Comment by DiscostewSM** [comment]
I updated to 11.3, and I also updated HBL to v1.3. After the payload is downloaded for me, I get this sequence of events on the top screen....

```
00000000
01fa1000

searching for target...

the homemenu ropbin is ready.
```

After this, it errors out to the Home menu.

edit:

Scratch that. Had to update to latest Luma hourly build to get it working. Works now.

**Comment by ajite** [comment]
I got the same issue than @DiscostewSM . The error message on the home screen is:

"An error has occured. Please save your data in any software currently use, and then restart the system."

I used the HB Launcher CIA released 2 hours ago and updated Luma using the "Install normal version".

**Comment by FenrirWolf** [comment]
You want to use *nightly*, not the normal release. Alternatively you can disable the L2 cache option.

**Comment by ajite** [comment]
It works. Thanks for the support :)

**Comment by Rowlet700** [comment]
Thanks to everyone, the hblauncher_loader works now.
But I just can't seem to really configure Luma3ds options...
![kakaotalk_20170211_182030124](https://cloud.githubusercontent.com/assets/25684207/22852770/e13492de-f086-11e6-89d8-317fa5b1fc7d.jpg)
Can anyone help me?

**Comment by Rowlet700** [comment]
Out-of-region titles do not work anymore. ;(

**Comment by FenrirWolf** [comment]
Luma issues should probably be taken to Luma's page.

**Comment by Rowlet700** [comment]
Thanks. Will do:)
