### ISSUE TITLE
No longer compiles on latest libctru/devkitarm

### ISSUE THREAD

**Issue by ApacheThunder** [yellows8/hblauncher_loader#6]
This appears to be an issue with how this gets along with my current build environment. Currently using Windows 7. CakesFW/ReiNand/rxTools all compile correctly for me. I was able to compile this awhile back. but something changed and it no longer compiles. Build log attached as a file.

[buildlog.txt](https://github.com/yellows8/hblauncher_loader/files/98652/buildlog.txt)

Appears to be an issue with libctru. But I recall updating to libctru 1.1.0 specifically because this wouldn't compile on the older one I had. Odd that it's suddenly not working again. I'm using libctru 1.1.0 and devkitarm/devkitpro release 45.

Last time I compiled this was late last year I believe.

**Comment by yellows8** [comment]
........ Build with latest git not the v1.0 tag.

**Comment by ApacheThunder** [comment]
Hmm thought I was using latest. Synced with Github Desktop app (that program is god awful though. Doesn't even sync changes to submodules correctly. :(

I'll delete and reclone this and see if that helps

**Comment by ApacheThunder** [comment]
I give up, Downloaded and compiled libctru instead of using 1.1.0 release build. Redownloaded hblauncher...Same error. :(

**Comment by profi200** [comment]
With just git installed in a terminal "git pull" ;) You can't get simpler and faster than that. The commandline git may be confusing at first but you get used to it.

**Comment by ApacheThunder** [comment]
What path do I provide to GIT? I used the download zip from website instead and it compiles now. However now makerom crashes which I think may still occur even if I use git pull correctly...

**Comment by ApacheThunder** [comment]
It's not working. I've looked up the command and I appear to be using it correctly. I give it this:

"git pull https://github.com/yellows8/hblauncher_loader.git"

Same error "Not a git repository". Perhaps the syntax isn't right but I'm not seeing the mistake....t

**Comment by profi200** [comment]
Normally it works like this (at least here):

1. Right click in the dir you want to download the repo to (if you have the repo already do this in the dir of the repo).
2. Click open git bash here.
3. If you don't already have the repo type git clone <repo URL>, otherwise git pull to get the latest changes.

git must be installed for this of course.

**Comment by hartmannaf** [comment]
You cant use git inside of zip downloaded repositorys, to use git pull you need to clone the repository using git clone. If you use the recursive flag, you will autodownload all submodules.

**Comment by ApacheThunder** [comment]
Ok thanks. I git clone (with recursive too even though this one doesn't have submodules), then git pull and it worked then.

But makerom still crashes when it attempts to build the CIA. :(

**Comment by yellows8** [comment]
Your using an outdated makerom build then.

**Comment by ApacheThunder** [comment]
Where can I find the latest? As far as I can tell makerom was updated to the current build when I updated devkitarm/devkitpro to release 45. So I don't see where it's outdated. The original github (at least the one I found) appears to be older then the one I have....

**Comment by ApacheThunder** [comment]
Ok found the correct github for make rom. (https://github.com/profi200/Project_CTR/releases)

It builds the CIA without crashing now. Thanks for putting up with my noobery when it came to compiling this. :P
