### ISSUE TITLE
Request: change to steveice10's buildtools to make building more smooth

### ISSUE THREAD

**Issue by favna** [yellows8/hblauncher_loader#61]
Title really says it all. I would like to request the building method to change to [steveice10's buildtools](https://github.com/Steveice10/buildtools/tree/master) to make building a very smooth and future proof experience. Furthermore this will ensure hblauncherloader will include the (beautiful) new homebrew logo that Steveice10 accepted on the repo not too long ago (made by PabloMK7, same guy who made the FBI banner among other things)

`git submodule add https://github.com/Steveice10/buildtools.git`

Updating a git submodule is done by

```
cd <folder_for_submodule> ('buildtools' in this case)
git fetch
git pull
```

As a last side-request I would like to ask you to include PabloMK7's 3D banner for the homebrew launcher loader, for buildtools this will have to be a cgfx file, which I have for you as attached (in a zip for uploading purposes). The cgfx has been obtained by decrypting and extracting the cia provided by PabloMK7 on the GBATemp thread where he released this version then using 3dsexplorer to get the file from the banner.bnr

{LINK REMOVED}

**Comment by yellows8** [comment]
Never.

Also, that logo is staying out of this repo since AFAIK the only tools for creating animated logos would be in CTRSDK.
