### ISSUE TITLE
Hombrew failed to download playload with HTTP

### ISSUE THREAD

**Issue by m-marius92** [yellows8/hblauncher_loader#65]
I hacked my o3ds by following this guide  http://3ds.guide
I am stucked at 
Section VII - DSP Dump
Launch the Homebrew Launcher from the home menu 
by the following URLhttps://3ds.guide/installing-arm9loaderhax

![homebrew error](https://cloud.githubusercontent.com/assets/27150977/24839174/ede4c75a-1d55-11e7-8878-5eb888b23545.jpg)

I am on Sys 7.1.0-15E

Please forgive english is not my language.

Do NOT ask about {supported system-versions} here for *hax payload, completely wrong place for that.

**Comment by yellows8** [comment]
"7.1.0-15E" .........

**Comment by blargnaut** [comment]
I have the same issue currently; I am not at all tech savvy, and my friend installed homebrew to my 3ds, so I have no idea what to do.  If someone could take the time to email me at blargnaut@live.com and give me simple steps to fix the issue, I would greatly appreciate it.
