### ISSUE TITLE
'Something failed' error on system with Luma and A9LH

### ISSUE THREAD

**Issue by kaimakes** [yellows8/hblauncher_loader#67]
00000000
01fa1000
c921081a

Something failed :<
please report error code above
-
Managed to get this error randomly. I tried reinstalling, everything. System is locked up.

**Comment by yellows8** [comment]
v11.4?

**Comment by kaimakes** [comment]
Just checked - bad news. Looks like it updated to 11.4, yeah.

**Comment by kaimakes** [comment]
11.4.0-37 to be exact. I'm on an O3DS XL EUR.

**Comment by yellows8** [comment]
\*hax payload doesn't support that currently.
