### ISSUE TITLE
No 10.5 support yet

### ISSUE THREAD

**Issue by EpicLPer** [yellows8/hblauncher_loader#7]
Even tho Ninjhax 2 supports 10.5 already the app says that there is no payload available so far for it via the server.
Please update this, thanks.

**Comment by yellows8** [comment]
Someone already tested it on v10.5 and it worked fine.....

**Comment by EpicLPer** [comment]
10.5 E?

**Comment by yellows8** [comment]
Probably. It also works fine on my USA nandimage.

What's the exact error message?(Could be just your Internet-connection)

**Comment by profi200** [comment]
Tested and confirmed working on 10.5.0-30E New 3DS.

**Comment by EpicLPer** [comment]
Yep, working here again now... Not sure what the problem was, weird...
