### ISSUE TITLE
Homebrew doesn't have access to CFGNOR service

### ISSUE THREAD

**Issue by natinusala** [yellows8/hblauncher_loader#72]
I wrote a simple addon which reads the WiFi configurations from the NVRAM by using the CFG:NOR service. 

It works when I build the homebrew as a CIA but it doesn't work when launching it from the HBL : the CFG:NOR service fails to initialize, error code 0xD8E06406. 

I tried to recompile HBL after adding the cfg:nor service to the RSF file, with no luck (same error).

**Comment by yellows8** [comment]
Run it under the system-settings title. Completely unrelated to this repo - what hblauncher_loader has access to doesn't affect homebrew loaded by \*hax payload.

**Comment by natinusala** [comment]
I was unsure of where to post this, sorry. But thanks for the tip ^^
