### ISSUE TITLE
11.4 error

### ISSUE THREAD

**Issue by DarkDragon32** [yellows8/hblauncher_loader#73]
I have an error code everytime i open homebrew
00000000
01fa1000
c921081a

**Comment by qwertyatom100** [comment]
Are you using an Old 3DS?

**Comment by DarkDragon32** [comment]
Yes

**Comment by qwertyatom100** [comment]
Then you need to manually download the 11.2 otherapp payload for your region and rename it `OLD-11-4-0-37-[region].bin` and put it in the `hblauncherloader` folder on your SD card, as homebrew doesn't work with 11.4 Old 3DS but you have CFW.

**Comment by DarkDragon32** [comment]
The error is gone but now the bottom screen stays red and the top screen stays black

**Comment by DarkDragon32** [comment]
if you know why it does this could you tell me how to fix it

**Comment by qwertyatom100** [comment]
Can you try and update your `boot.3dsx` file on the root of your SD card?

**Comment by DarkDragon32** [comment]
I fixed it
