### ISSUE TITLE
To-resolve-the-homebrew-launcher-error-11.4

### ISSUE THREAD

**Issue by ghost** [yellows8/hblauncher_loader#78]
I think I have found the solution to this error.
https://github.com/ianmacavilca/To-resolve-the-homebrew-launcher-error-11.4

**Comment by Committee** [comment]
This only resolves the issue with O3DS not launching HBL on A9LH systems.

Use the new HBL launcher for B9S.

**Comment by ghost** [comment]
the process is equal in N3DS and O3DS. Im using B9S, homebrew launcher for 11.3.0.36 and Luma 7.1
