### ISSUE TITLE
Randomly boots to Download Play

### ISSUE THREAD

**Issue by harvestry-of-ghosts** [yellows8/hblauncher_loader#8]
Launching the cia randomly boots to Download Play instead of HBL. When this happens the L+R+D+B combo does not work to reset & the power button must be held to shut down the 3DS.

N3DS-XL
9.2 Sysnand
10.5 Emunand (ReiNand 3.2b)
CtrBootManager 1.7
Suloku's HBL

**Comment by yellows8** [comment]
Process-takeover randomly failing has nothing to do with hblauncher_loader itself.

https://github.com/smealum/ninjhax2.x
