### ISSUE TITLE
Can't get Hans to pop up on homebrew menu

### ISSUE THREAD

**Issue by wolftamer86** [yellows8/hblauncher_loader#87]
Do NOT ask about {supported system-versions} here for *hax payload, completely wrong place for that.
Love using Hans for region lock and overclocking fps, just reinstalled ninjhax on 11.6 & I can't get the launcher :-(

**Comment by ObscenityIB** [comment]
i cant get hans to show up either, i have no idea why

**Comment by wolftamer86** [comment]
hey i found a solution that worked for me 


Sent from Yahoo Mail for iPhone


On Friday, October 20, 2017, 10:33 AM, ObscenityIB <notifications@github.com> wrote:


i cant get hans to show up either, i have no idea why
