### ISSUE TITLE
Need Help; no experience in this field

### ISSUE THREAD

**Issue by blargnaut** [yellows8/hblauncher_loader#88]
Do NOT ask about {supported system-versions} here for *hax payload, completely wrong place for that.

Before I start, I can say that I noticed that several others with the same problem have had there issues closed, as well as the fact that I know little to nothing about this field (a friend originally installed HB for me); so I do not know if my problem falls under the (supported system-versions) category.  I have absolutely no idea how to fix this, and honestly can hardly navigate my own computer because of my limited experience with them, including any other similar electronics.  My hope is that someone can give me straightforward and hopefully simple steps to fix this; or at the least, point me in the right direction.

I will greatly appreciate the time and effort of any of the community here that can help me, and the most  I can do is provide the requested picture of my 3ds.

Thanks for reading,
blargnaut
![3ds hb error message](https://user-images.githubusercontent.com/36174682/35945221-687a1daa-0c2d-11e8-8387-fcb631808aac.jpg)

**Comment by ghost** [comment]
I'm getting the same issue. May have to do with the new GitHub changes I think that break some homebrew.

**Comment by blargnaut** [comment]
Any idea if there's a fix? I saw two other posts with the same problem but the issues are closed for them; I don't know if that means it was resolved or not...

**Comment by ghost** [comment]
All I can say is download the payload for your homebrew version and stick it in the hblauncherloader folder. You might have to rename the bin to OLD-11-6-0-39-USA.bin or something, or NEW if it's a New 3DS, I didn't bother testing.

[Scroll down on this page to find the payloads](http://smealum.github.io/3ds/).

**Comment by blargnaut** [comment]
Okay, thanks a bunch, I'll give it a try.

**Comment by blargnaut** [comment]
That fixed it! I downloaded the otherapp and replaced the old file on my sd card, and renamed the file OLD-11-6-0-39-USA. Thank you so much for the input!
