### ISSUE TITLE
[o3ds/o3dsxl] hans screenshot tool only extracting black pictures

### ISSUE THREAD

**Issue by ellie3ds** [yellows8/hblauncher_loader#93]
o3ds xl version 11.6 using oot3dhax & o3ds version 11.4 using soundhax

Both of my systems only extract black screenshots no matter the working title I put in. I've tried Animal Crossing: Welcome Amiibo, Story of Seasons, and Harvest Moon: A New Beginning (all physical copies). All of these titles run perfectly fine in Hans, and when I click the Home button it freezes like it should and takes a screenshot. However, after powering off the system and opening Homebrew again and using the screenshot tool to extract them, all of the screenshots appear black on my screen and on my SD card on my computer.

Any guidance or help would be much appreciated.

**Comment by yellows8** [comment]
wrong repo
