### ISSUE TITLE
Problem with HB launcher

### ISSUE THREAD

**Issue by SuperTemich2005** [yellows8/hblauncher_loader#96]
New nintendo 3DS XL, 11.7.0-39E, language: russian. Connected to wi-fi. I have downloaded .cia launcher from http://smealum.github.io/3ds/ via FBI. Luma is 9.0
![p80520-194040 1](https://user-images.githubusercontent.com/39464061/40281129-28c59cbe-5c66-11e8-9023-8a62367c53e8.jpg)

**Comment by SuperTemich2005** [comment]
(fur under touch screen belong to my cat by the way)

**Comment by SuperTemich2005** [comment]
Hey, but what 'bout the answer? Well, I think that I should solve 'dis problem without any help.

**Comment by yellows8** [comment]
See the other issues with same error in title ...

**Comment by SuperTemich2005** [comment]
OK, I have updated a9lh to b9s and it worked!
